apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: lobster-python 
  janus-idp.io/tekton: lobster-python
  backstage.io/kubernetes-id: lobster-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: lobster-python
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  